export const footerLinks = [
  {
    title: 'About',
    links: [
      { title: 'How it works', url: '/' },
      { title: 'Featured', url: '/' },
      { title: 'Partnership', url: '/' },
      { title: 'Business Relation', url: '/' },
    ],
  },
  {
    title: 'Company',
    links: [
      { title: 'Events', url: '/' },
      { title: 'Blog', url: '/' },
      { title: 'Podcast', url: '/' },
      { title: 'Invite a friend', url: '/' },
    ],
  },
  {
    title: 'Socials',
    links: [
      { title: 'Discord', url: '/' },
      { title: 'Instagram', url: '/' },
      { title: 'Twitter', url: '/' },
      { title: 'Facebook', url: '/' },
    ],
  },
];

export const popularBrands = [
  {
    title: 'Harley Davidson',
    url: 'harley-davidson-logo.svg',
  },
  {
    title: 'Honda',
    url: '/honda-logo.svg',
  },
  {
    title: 'Yamaha',
    url: '/yamaha-logo.svg',
  },
  {
    title: 'Kawasaki',
    url: '/kawasaki-logo.svg',
  },
  {
    title: 'BMW',
    url: '/bmw-logo.svg',
  },
  {
    title: 'Ducati',
    url: '/ducati-logo.svg',
  },
];

export const testData = [
  {
    make: 'Honda',
    model: 'GB 500 Clubman',
    year: '1992',
    type: 'Classic',
    displacement: '498.0 ccm (30.39 cubic inches)',
    engine: 'Single cylinder, four-stroke',
    power: '38.0 HP (27.7  kW)) @ 7500 RPM',
    top_speed: '166.0 km/h (103.1 mph)',
    compression: '8.9:1',
    bore_stroke: '92.0 x 75.0 mm (3.6 x 3.0 inches)',
    valves_per_cylinder: '4',
    fuel_control: 'Overhead Cams (OHC)',
    cooling: 'Air',
    gearbox: '5-speed',
    transmission: 'Chain   (final drive)',
    front_tire: '90/90-18 ',
    rear_tire: '110/90-18 ',
    front_brakes: 'Single disc',
    rear_brakes: 'Expanding brake',
    total_weight: '179.0 kg (394.6 pounds)',
    fuel_capacity: '16.50 litres (4.36 US gallons)',
  },
  {
    make: 'Honda',
    model: 'GB 500 Clubman (reduced effect)',
    year: '1992',
    type: 'Classic',
    displacement: '498.0 ccm (30.39 cubic inches)',
    engine: 'Single cylinder, four-stroke',
    power: '27.0 HP (19.7  kW)) @ 6000 RPM',
    top_speed: '147.0 km/h (91.3 mph)',
    compression: '8.9:1',
    bore_stroke: '92.0 x 75.0 mm (3.6 x 3.0 inches)',
    valves_per_cylinder: '4',
    fuel_control: 'Overhead Cams (OHC)',
    cooling: 'Air',
    gearbox: '5-speed',
    transmission: 'Chain   (final drive)',
    front_tire: '90/90-18 ',
    rear_tire: '110/90-18 ',
    front_brakes: 'Single disc',
    rear_brakes: 'Expanding brake',
    total_weight: '179.0 kg (394.6 pounds)',
    fuel_capacity: '16.50 litres (4.36 US gallons)',
  },
  {
    make: 'Honda',
    model: 'GB 500 Clubman',
    year: '1989',
    type: 'Classic',
    displacement: '498.0 ccm (30.39 cubic inches)',
    engine: 'Single cylinder, four-stroke',
    power: '38.0 HP (27.7  kW))',
    top_speed: '166.0 km/h (103.1 mph)',
    compression: '8.9:1',
    bore_stroke: '92.0 x 75.0 mm (3.6 x 3.0 inches)',
    valves_per_cylinder: '2',
    fuel_system: 'Carburettor',
    fuel_control: 'Overhead Cams (OHC)',
    cooling: 'Air',
    front_tire: '90/90-18 ',
    rear_tire: '110/90-18 ',
    front_brakes: 'Single disc',
    rear_brakes: 'Expanding brake (drum brake)',
    dry_weight: '163.0 kg (359.4 pounds)',
    total_length: '2100 mm (82.7 inches)',
    total_width: '680 mm (26.8 inches)',
    fuel_capacity: '16.50 litres (4.36 US gallons)',
  },
  {
    make: 'Honda',
    model: 'GB 250 Clubman',
    year: '1985',
    type: 'Sport touring',
    displacement: '249.0 ccm (15.19 cubic inches)',
    engine: 'Single cylinder, four-stroke',
    power: '30.0 HP (21.9  kW)) @ 9500 RPM',
    top_speed: '152.9 km/h (95.0 mph)',
    valves_per_cylinder: '4',
    fuel_system: 'Carburettor. Twin Keihin 28.5mm',
    fuel_control: 'Double Overhead Cams/Twin Cam (DOHC)',
    lubrication: 'Wet sump',
    cooling: 'Air',
    gearbox: '6-speed',
    transmission: 'Chain   (final drive)',
    fuel_consumption: '3.61 litres/100 km (27.7 km/l or 65.16 mpg)',
    emission: '83.8 CO2 g/km. (CO2 - Carbon dioxide emission) ',
    rear_suspension: 'Twin shock',
    front_tire: '90/90-18 ',
    rear_tire: '110/90-18 ',
    front_brakes: 'Single disc. 2 piston',
    rear_brakes: 'Expanding brake (drum brake)',
    dry_weight: '130.0 kg (286.6 pounds)',
    fuel_capacity: '17.00 litres (4.49 US gallons)',
    starter: 'Electric',
  },
];
